import pytest
from config import load_parameters


def test_load_params():
    params = load_parameters()
    assert isinstance(params, dict)


def test_params_exist():
    params = load_parameters()
    assert 'DATASET_NAME' in list(params)
    assert 'SRC_LAN' in list(params)
    assert 'TRG_LAN' in list(params)
    assert 'DATA_ROOT_PATH' in list(params)
    assert 'TEXT_FILES' in list(params)
    assert 'INPUTS_IDS_DATASET' in list(params)
    assert 'OUTPUTS_IDS_DATASET' in list(params)
    assert 'INPUTS_IDS_MODEL' in list(params)
    assert 'OUTPUTS_IDS_MODEL' in list(params)
    assert 'METRICS' in list(params)
    assert 'EVAL_ON_SETS' in list(params)
    assert 'START_EVAL_ON_EPOCH' in list(params)
    assert 'EVAL_EACH_EPOCHS' in list(params)
    assert 'EVAL_EACH' in list(params)
    assert 'SAMPLING' in list(params)
    assert 'TEMPERATURE' in list(params)
    assert 'BEAM_SEARCH' in list(params)
    assert 'BEAM_SIZE' in list(params)
    assert 'OPTIMIZED_SEARCH' in list(params)
    assert 'LENGTH_PENALTY' in list(params)
    assert 'LENGTH_NORM_FACTOR' in list(params)
    assert 'COVERAGE_PENALTY' in list(params)
    assert 'COVERAGE_NORM_FACTOR' in list(params)
    assert 'NORMALIZE_SAMPLING' in list(params)
    assert 'ALPHA_FACTOR' in list(params)
    assert 'SAMPLE_ON_SETS' in list(params)
    assert 'N_SAMPLES' in list(params)
    assert 'START_SAMPLING_ON_EPOCH' in list(params)
    assert 'SAMPLE_EACH_UPDATES' in list(params)
    assert 'POS_UNK' in list(params)
    assert 'HEURISTIC' in list(params)
    assert 'ALIGN_FROM_RAW' in list(params)
    assert 'MAPPING' in list(params)
    assert 'TOKENIZATION_METHOD' in list(params)
    assert 'DETOKENIZATION_METHOD' in list(params)
    assert 'APPLY_DETOKENIZATION' in list(params)
    assert 'TOKENIZE_HYPOTHESES' in list(params)
    assert 'TOKENIZE_REFERENCES' in list(params)
    assert 'DATA_AUGMENTATION' in list(params)
    assert 'FILL' in list(params)
    assert 'PAD_ON_BATCH' in list(params)
    assert 'INPUT_VOCABULARY_SIZE' in list(params)
    assert 'MIN_OCCURRENCES_INPUT_VOCAB' in list(params)
    assert 'MAX_INPUT_TEXT_LEN' in list(params)
    assert 'OUTPUT_VOCABULARY_SIZE' in list(params)
    assert 'MIN_OCCURRENCES_OUTPUT_VOCAB' in list(params)
    assert 'MAX_OUTPUT_TEXT_LEN' in list(params)
    assert 'MAX_OUTPUT_TEXT_LEN_TEST' in list(params)
    assert 'LOSS' in list(params)
    assert 'CLASSIFIER_ACTIVATION' in list(params)
    assert 'OPTIMIZER' in list(params)
    assert 'LR' in list(params)
    assert 'CLIP_C' in list(params)
    assert 'CLIP_V' in list(params)
    assert 'SAMPLE_WEIGHTS' in list(params)
    assert 'LR_DECAY' in list(params)
    assert 'LR_GAMMA' in list(params)
    assert 'MAX_EPOCH' in list(params)
    assert 'BATCH_SIZE' in list(params)
    assert 'HOMOGENEOUS_BATCHES' in list(params)
    assert 'JOINT_BATCHES' in list(params)
    assert 'PARALLEL_LOADERS' in list(params)
    assert 'EPOCHS_FOR_SAVE' in list(params)
    assert 'WRITE_VALID_SAMPLES' in list(params)
    assert 'SAVE_EACH_EVALUATION' in list(params)
    assert 'EARLY_STOP' in list(params)
    assert 'PATIENCE' in list(params)
    assert 'STOP_METRIC' in list(params)
    assert 'MIN_DELTA' in list(params)
    assert 'MODEL_TYPE' in list(params)
    assert 'ENCODER_RNN_TYPE' in list(params)
    assert 'DECODER_RNN_TYPE' in list(params)
    assert 'INIT_FUNCTION' in list(params)
    assert 'SOURCE_TEXT_EMBEDDING_SIZE' in list(params)
    assert 'SRC_PRETRAINED_VECTORS' in list(params)
    assert 'SRC_PRETRAINED_VECTORS_TRAINABLE' in list(params)
    assert 'TARGET_TEXT_EMBEDDING_SIZE' in list(params)
    assert 'TRG_PRETRAINED_VECTORS' in list(params)
    assert 'TRG_PRETRAINED_VECTORS_TRAINABLE' in list(params)
    assert 'ENCODER_HIDDEN_SIZE' in list(params)
    assert 'BIDIRECTIONAL_ENCODER' in list(params)
    assert 'N_LAYERS_ENCODER' in list(params)
    assert 'BIDIRECTIONAL_DEEP_ENCODER' in list(params)
    assert 'DECODER_HIDDEN_SIZE' in list(params)
    assert 'N_LAYERS_DECODER' in list(params)
    assert 'ADDITIONAL_OUTPUT_MERGE_MODE' in list(params)
    assert 'ATTENTION_SIZE' in list(params)
    assert 'SKIP_VECTORS_HIDDEN_SIZE' in list(params)
    assert 'INIT_LAYERS' in list(params)
    assert 'DEEP_OUTPUT_LAYERS' in list(params)
    assert 'WEIGHT_DECAY' in list(params)
    assert 'RECURRENT_WEIGHT_DECAY' in list(params)
    assert 'DROPOUT_P' in list(params)
    assert 'RECURRENT_INPUT_DROPOUT_P' in list(params)
    assert 'RECURRENT_DROPOUT_P' in list(params)
    assert 'USE_NOISE' in list(params)
    assert 'NOISE_AMOUNT' in list(params)
    assert 'USE_BATCH_NORMALIZATION' in list(params)
    assert 'BATCH_NORMALIZATION_MODE' in list(params)
    assert 'USE_PRELU' in list(params)
    assert 'USE_L2' in list(params)
    assert 'EXTRA_NAME' in list(params)
    assert 'MODEL_NAME' in list(params)
    assert 'STORE_PATH' in list(params)
    assert 'DATASET_STORE_PATH' in list(params)
    assert 'SAMPLING_SAVE_MODE' in list(params)
    assert 'VERBOSE' in list(params)
    assert 'RELOAD' in list(params)
    assert 'RELOAD_EPOCH' in list(params)
    assert 'REBUILD_DATASET' in list(params)
    assert 'MODE' in list(params)
    assert 'TRAIN_ON_TRAINVAL' in list(params)
    assert 'FORCE_RELOAD_VOCABULARY' in list(params)


def test_params_type():
    params = load_parameters()
    assert isinstance(params['DATASET_NAME'], str)
    assert isinstance(params['SRC_LAN'], str)
    assert isinstance(params['TRG_LAN'], str)
    assert isinstance(params['DATA_ROOT_PATH'], str)
    assert isinstance(params['TEXT_FILES'], dict)
    assert isinstance(params['INPUTS_IDS_DATASET'], list)
    assert isinstance(params['OUTPUTS_IDS_DATASET'], list)
    assert isinstance(params['INPUTS_IDS_MODEL'], list)
    assert isinstance(params['OUTPUTS_IDS_MODEL'], list)
    assert isinstance(params['METRICS'], list)
    assert isinstance(params['EVAL_ON_SETS'], list)
    assert isinstance(params['START_EVAL_ON_EPOCH'], int)
    assert isinstance(params['EVAL_EACH_EPOCHS'], bool)
    assert isinstance(params['EVAL_EACH'], int)
    assert isinstance(params['SAMPLING'], str)
    assert isinstance(params['TEMPERATURE'], int)
    assert isinstance(params['BEAM_SEARCH'], bool)
    assert isinstance(params['BEAM_SIZE'], int)
    assert isinstance(params['OPTIMIZED_SEARCH'], bool)
    assert isinstance(params['LENGTH_PENALTY'], bool)
    assert isinstance(params['LENGTH_NORM_FACTOR'], float)
    assert isinstance(params['COVERAGE_PENALTY'], bool)
    assert isinstance(params['COVERAGE_NORM_FACTOR'], float)
    assert isinstance(params['NORMALIZE_SAMPLING'], bool)
    assert isinstance(params['ALPHA_FACTOR'], float)
    assert isinstance(params['SAMPLE_ON_SETS'], list)
    assert isinstance(params['N_SAMPLES'], int)
    assert isinstance(params['START_SAMPLING_ON_EPOCH'], int)
    assert isinstance(params['SAMPLE_EACH_UPDATES'], int)
    assert isinstance(params['POS_UNK'], bool)
    assert isinstance(params['HEURISTIC'], int)
    assert isinstance(params['ALIGN_FROM_RAW'], bool)
    assert isinstance(params['MAPPING'], str)
    assert isinstance(params['TOKENIZATION_METHOD'], str)
    assert isinstance(params['DETOKENIZATION_METHOD'], str)
    assert isinstance(params['APPLY_DETOKENIZATION'], bool)
    assert isinstance(params['TOKENIZE_HYPOTHESES'], bool)
    assert isinstance(params['TOKENIZE_REFERENCES'], bool)
    assert isinstance(params['DATA_AUGMENTATION'], bool)
    assert isinstance(params['FILL'], str)
    assert isinstance(params['PAD_ON_BATCH'], bool)
    assert isinstance(params['INPUT_VOCABULARY_SIZE'], int)
    assert isinstance(params['MIN_OCCURRENCES_INPUT_VOCAB'], int)
    assert isinstance(params['MAX_INPUT_TEXT_LEN'], int)
    assert isinstance(params['OUTPUT_VOCABULARY_SIZE'], int)
    assert isinstance(params['MIN_OCCURRENCES_OUTPUT_VOCAB'], int)
    assert isinstance(params['MAX_OUTPUT_TEXT_LEN'], int)
    assert isinstance(params['MAX_OUTPUT_TEXT_LEN_TEST'], int)
    assert isinstance(params['LOSS'], str)
    assert isinstance(params['CLASSIFIER_ACTIVATION'], str)
    assert isinstance(params['OPTIMIZER'], str)
    assert isinstance(params['LR'], float)
    assert isinstance(params['CLIP_C'], float)
    assert isinstance(params['CLIP_V'], float)
    assert isinstance(params['SAMPLE_WEIGHTS'], bool)
    assert params['LR_DECAY'] is None
    assert isinstance(params['LR_GAMMA'], float)
    assert isinstance(params['MAX_EPOCH'], int)
    assert isinstance(params['BATCH_SIZE'], int)
    assert isinstance(params['HOMOGENEOUS_BATCHES'], bool)
    assert isinstance(params['JOINT_BATCHES'], int)
    assert isinstance(params['PARALLEL_LOADERS'], int)
    assert isinstance(params['EPOCHS_FOR_SAVE'], int)
    assert isinstance(params['WRITE_VALID_SAMPLES'], bool)
    assert isinstance(params['SAVE_EACH_EVALUATION'], bool)
    assert isinstance(params['EARLY_STOP'], bool)
    assert isinstance(params['PATIENCE'], int)
    assert isinstance(params['STOP_METRIC'], str)
    assert isinstance(params['MIN_DELTA'], float)
    assert isinstance(params['MODEL_TYPE'], str)
    assert isinstance(params['ENCODER_RNN_TYPE'], str)
    assert isinstance(params['DECODER_RNN_TYPE'], str)
    assert isinstance(params['INIT_FUNCTION'], str)
    assert isinstance(params['SOURCE_TEXT_EMBEDDING_SIZE'], int)
    assert params['SRC_PRETRAINED_VECTORS'] is None
    assert isinstance(params['SRC_PRETRAINED_VECTORS_TRAINABLE'], bool)
    assert isinstance(params['TARGET_TEXT_EMBEDDING_SIZE'], int)
    assert params['TRG_PRETRAINED_VECTORS'] is None
    assert isinstance(params['ENCODER_HIDDEN_SIZE'], int)
    assert isinstance(params['BIDIRECTIONAL_ENCODER'], bool)
    assert isinstance(params['N_LAYERS_ENCODER'], int)
    assert isinstance(params['BIDIRECTIONAL_DEEP_ENCODER'], bool)
    assert isinstance(params['DECODER_HIDDEN_SIZE'], int)
    assert isinstance(params['N_LAYERS_DECODER'], int)
    assert isinstance(params['ATTENTION_SIZE'], int)
    assert isinstance(params['ADDITIONAL_OUTPUT_MERGE_MODE'], str)
    assert isinstance(params['SKIP_VECTORS_HIDDEN_SIZE'], int)
    assert isinstance(params['INIT_LAYERS'], list)
    assert isinstance(params['DEEP_OUTPUT_LAYERS'], list)
    assert isinstance(params['WEIGHT_DECAY'], float)
    assert isinstance(params['RECURRENT_WEIGHT_DECAY'], float)
    assert isinstance(params['DROPOUT_P'], float)
    assert isinstance(params['RECURRENT_INPUT_DROPOUT_P'], float)
    assert isinstance(params['RECURRENT_DROPOUT_P'], float)
    assert isinstance(params['USE_NOISE'], bool)
    assert isinstance(params['NOISE_AMOUNT'], float)
    assert isinstance(params['USE_BATCH_NORMALIZATION'], bool)
    assert isinstance(params['BATCH_NORMALIZATION_MODE'], int)
    assert isinstance(params['USE_PRELU'], bool)
    assert isinstance(params['USE_L2'], bool)
    assert isinstance(params['EXTRA_NAME'], str)
    assert isinstance(params['MODEL_NAME'], str)
    assert isinstance(params['STORE_PATH'], str)
    assert isinstance(params['DATASET_STORE_PATH'], str)
    assert isinstance(params['SAMPLING_SAVE_MODE'], str)
    assert isinstance(params['VERBOSE'], int)
    assert isinstance(params['RELOAD'], int)
    assert isinstance(params['RELOAD_EPOCH'], bool)
    assert isinstance(params['REBUILD_DATASET'], bool)
    assert isinstance(params['MODE'], str)
    assert isinstance(params['TRAIN_ON_TRAINVAL'], bool)
    assert isinstance(params['FORCE_RELOAD_VOCABULARY'], bool)


if __name__ == '__main__':
    pytest.main([__file__])
